wandb_version: 1

epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 256
n_covariates:
  desc: null
  value: 34
n_species:
  desc: null
  value: 10038
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682412641.157623
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.16
      5: 0.15.0
      8:
      - 5
